# Copyright (c) 2021 Accurics - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    accurics.com/app: in-cluster-kubescanner
  name: kubescanner-view-default
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: in-cluster-kubescanner
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: accurics-view
  apiGroup: rbac.authorization.k8s.io
